import piexif from 'piexifjs';
import type { ScrubOptions, FieldGroup } from '../types';
import { classify } from '../sensitivity';
import { bytesToBinary, binaryToBytes, segmentStrip, type SegmentStripConfig } from './jpeg-util';

// IFD-pointer tags are regenerated by piexif.dump — never copy them manually.
const POINTER_TAGS = new Set([0x8769, 0x8825, 0xa005]);

/** True if every removable group is flagged for removal (true "strip all"). */
function isStripEverything(o: ScrubOptions): boolean {
  return (
    o.removeGps &&
    o.removeCamera &&
    o.removeDateTime &&
    o.removeSoftware &&
    o.removeDevice &&
    o.removeThumbnail &&
    o.removeIptc &&
    o.removeXmp &&
    o.removeIcc &&
    o.removeOrientation
  );
}

/** Whether a logical group should be removed under the given options. */
function removeGroup(group: FieldGroup, o: ScrubOptions): boolean {
  switch (group) {
    case 'gps':
      return o.removeGps;
    case 'camera':
      return o.removeCamera;
    case 'datetime':
      return o.removeDateTime;
    case 'software':
      return o.removeSoftware;
    case 'device':
      return o.removeDevice;
    case 'thumbnail':
      return o.removeThumbnail;
    case 'iptc':
      return o.removeIptc;
    case 'xmp':
      return o.removeXmp;
    case 'icc':
      return o.removeIcc;
    case 'orientation':
      return o.removeOrientation;
    case 'image':
    case 'other':
    default:
      return false; // descriptive / unknown EXIF tags are kept unless full strip-all
  }
}

/**
 * Scrub a JPEG **losslessly** (pixel/scan data is never re-encoded).
 *
 * - Full strip-all → drop every metadata-bearing marker segment (EXIF/XMP/ICC/
 *   IPTC/comment/unknown APPn). The JFIF density (APP0) and Adobe colour-
 *   transform (APP14) segments are intentionally kept: they carry no identifying
 *   data and are needed to render the image correctly.
 * - Otherwise → rebuild a minimal EXIF block keeping only the groups the user
 *   chose to keep (e.g. orientation), and drop the rest plus the other metadata
 *   segments (XMP/ICC/IPTC/comment) per the options.
 */
export function scrubJpeg(bytes: Uint8Array, opts: ScrubOptions): Uint8Array {
  if (isStripEverything(opts)) {
    return segmentStrip(bytes, allDrops());
  }

  // Read existing EXIF (tolerant of images with none).
  let dict;
  try {
    dict = piexif.load(bytesToBinary(bytes));
  } catch {
    dict = null;
  }

  const cfg: SegmentStripConfig = {
    dropExif: true, // always strip, then re-add the filtered minimal block
    dropXmp: opts.removeXmp,
    dropIcc: opts.removeIcc,
    dropIptc: opts.removeIptc,
    dropJfxxThumb: opts.removeThumbnail,
    dropComment: opts.removeSoftware,
    dropUnknownApp: opts.removeSoftware || opts.removeDevice,
  };
  const stripped = segmentStrip(bytes, cfg);

  if (!dict) return stripped;

  const rebuilt = filterExif(dict, opts);
  if (!hasAnyExif(rebuilt)) return stripped;

  try {
    const exifBytes = piexif.dump(rebuilt);
    const outBin = piexif.insert(exifBytes, bytesToBinary(stripped));
    return binaryToBytes(outBin);
  } catch {
    // If re-dumping fails, prefer over-stripping (no metadata) to failing.
    return stripped;
  }
}

type ExifDict = ReturnType<typeof piexif.load>;

/** Build a new EXIF dict keeping only the groups the user did not remove. */
function filterExif(dict: ExifDict, opts: ScrubOptions): Partial<ExifDict> {
  const out: Partial<ExifDict> = {
    '0th': {},
    Exif: {},
    GPS: {},
    Interop: {},
    '1st': {},
    thumbnail: null,
  };

  out['0th'] = filterIfd(dict['0th'], 'Image', opts);
  out.Exif = filterIfd(dict.Exif, 'Exif', opts);

  if (!opts.removeGps) out.GPS = dict.GPS;
  if (!opts.removeThumbnail) {
    out['1st'] = dict['1st'];
    out.thumbnail = dict.thumbnail;
  }
  // Interop is descriptive; keep it unless camera info is being removed.
  if (!opts.removeCamera) out.Interop = dict.Interop;

  return out;
}

function filterIfd(ifd: Record<number, unknown>, table: string, opts: ScrubOptions): Record<number, unknown> {
  const result: Record<number, unknown> = {};
  for (const [tagStr, value] of Object.entries(ifd)) {
    const tag = Number(tagStr);
    if (POINTER_TAGS.has(tag)) continue; // regenerated by dump
    const name = piexif.TAGS[table]?.[tag]?.name ?? String(tag);
    const group = classify(name).group;
    if (!removeGroup(group, opts)) result[tag] = value;
  }
  return result;
}

function hasAnyExif(d: Partial<ExifDict>): boolean {
  const ifds: (keyof ExifDict)[] = ['0th', 'Exif', 'GPS', 'Interop', '1st'];
  for (const k of ifds) {
    const v = d[k] as Record<number, unknown> | undefined;
    if (v && Object.keys(v).length > 0) return true;
  }
  return !!d.thumbnail;
}

function allDrops(): SegmentStripConfig {
  return {
    dropExif: true,
    dropXmp: true,
    dropIcc: true,
    dropIptc: true,
    dropJfxxThumb: true,
    dropComment: true,
    dropUnknownApp: true,
  };
}
